### ISSUE TITLE
tokens only delimited by space?

### ISSUE THREAD

**Issue by asmwarrior** [fairyWreath/Trie-Lexer#1]
```
~> a+b
Source: a+b
Token string [a+b], Token type [1] at line 1
EOF found
~> a + b
Source: a + b
Token string [a], Token type [1] at line 1
Token string [+], Token type [2] at line 1
Token string [b], Token type [1] at line 1
EOF found
~>
```
This is the log I try to test. When parse the string "a+b", it get the whole token. Is this by design?

**Comment by fairywreath** [comment]
Hello,

Yes, that is by design. The scanner skips all space, tab, and new lines characters; they are treated as delimiters.  If you would like to  recognize spaces or change the delimiter type(s),  you can disable the lexer to skip white spaces and add tokens for spaces, tabs, etc. You would have to increase the the maximum number of children nodes for a trie node(they currently support only 94 ascii characters) and completely change they way how identifiers are scanned.

**Comment by asmwarrior** [comment]
Thanks for the reply.
For an identifier, I would it could be something like ` [a-zA-Z_][0-9a-zA-Z_]*`, and for a keyword, it would be some special identifier such as `for` or `class` in C++ language.

I'm not sure whether trie-lexer is faster than a normal lexer like `flex` or `re2c`, do you know the performance?

**Comment by fairywreath** [comment]
This lexer is much slower than ```flex```, since it uses a trie to store the lexeme.  It took me around ~30s to scan ~1 million lines of C code.  It is also less efficient memory-wise. The biggest advantage of this lexer is that adding identifiers/keywords is really easy/quick, since you simply insert it into the trie, and you can even possibly do this at runtime.

In addition to alphanumeric characters the lexer allows identifiers to contain other characters like ```{ ] * -``` although they would need to  be separated with spaces as a delimiter.  To prevent spaces from delimiting you would have to limit identifiers/keyword to eg. only alphanumeric characters so they do not clash with other tokens such as ```+``` or ```*```.

**Comment by asmwarrior** [comment]
Thanks for the explanation. 
BTW: For a normal compiler, especially for checking whether an identifier is a keyword, a hash table is used instead of a trie.

**Comment by fairywreath** [comment]
Yes I am aware of that. I simply thought it would be cool to implement it in a trie data structure. Thanks anyways!
